<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>12</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\ComfyGizmo\ComfyLib\Collections\PieceSelectionCache.cs" Link="PieceSelectionCache.cs" />
  </ItemGroup>
</Project>
