using System.Collections.Generic;
using System.Collections.Specialized;

namespace PlantThings {
  static class Name {
    static readonly Dictionary<string, string> _displayNames = new Dictionary<string, string>() {
      { "custompiece_fancypot", "Fancy Pot" },
      { "custompiece_fancypotl", "Fancy Pot (L)" },
      { "custompiece_hangingpot_large", "Hangin Pot (L)" },
      { "custompiece_hangingpot_small", "Hanging Pot (S)" },
      { "custompiece_tcpot1", "Clay Pot 1" },
      { "custompiece_tcpot1l", "Clay Pot 1 (L)" },
      { "custompiece_tcpot2", "Clay Pot 2" },
      { "custompiece_tcpot2l", "Clay Pot 2 (L)" },
      { "custompiece_tcpot3", "Clay Pot 3" },
      { "custompiece_tcpot3l", "Clay Pot 3 (L)" },
      { "custompiece_tcpotrectangle", "Clay Pot Rectangle" },
      { "custompiece_tcpotrectanglel", "Clay Pot Rectangle (L)" },
      { "custompiece_tcpotsquare", "Clay Pot Square" },
      { "custompiece_tcpotsquarel", "Clay Pot Square (L)" },
      { "$custompiece_stump1", "Stump 1" },
      { "$custompiece_stump2", "Stump 2" },
      { "$custompiece_stump3", "Stump 3" },
      { "$custompiece_stump4", "Stump 4" },
      { "$custompiece_stump5", "Stump 5" },
      { "$custompiece_stump6", "Stump 6" },
      { "$custompiece_stump7", "Stump 7" },
      { "$custompiece_log1", "Log 1" },
      { "$custompiece_log2", "Log 2" },
      { "$custompiece_log3", "Log 3" },
      { "$custompiece_log4", "Log 4" },
      { "$custompiece_log5", "Log 5" },
      { "$custompiece_stumptable", "Stump Table" },
      { "$custompiece_grassblock_small", "Grassblock (S)" },
      { "$custompiece_grassblock_medium", "Grassblock (M)" },
      { "$custompiece_grassblock_large", "Grassblock (L)" },
      { "$custompiece_dirtblock_small", "Dirtblock (S)" },
      { "$custompiece_dirtblock_medium", "Dirtblock (M)" },
      { "$custompiece_dirtblock_large", "Dirtblock (L)" },
      { "$custompiece_grassblock_small_test", "Grassblock Test (S)" },
      { "$custompiece_grassblock_small_test2", "Grassblock Test 2 (S)" },
      { "custompiece_vines3", "Vines 3" },
      { "custompiece_vines4", "Vines 4" },
      { "custompiece_vines5", "Vines 5" },
      { "custompiece_vines6", "Vines 6" },
      { "custompiece_vines7", "Vines 7" },
      { "custompiece_vines10", "Vines 10" },
      { "custompiece_vines11", "Vines 11" },
      { "custompiece_vines12", "Vines 12" },
      { "custompiece_vinesvanilla", "Vines Vanilla" },
      { "custompiece_vinesvanillabig", "Vines Vanilla (L)" },
      { "custompiece_vinesvanillastretched", "Vines Vanilla Stretched" },
      { "custompiece_vines1.2", "Vines 1.2" },
      { "custompiece_vines1", "Vines 1" },
      { "custompiece_hangingplant", "Hanging Plant" },
      { "custompiece_hangingplant1.2", "Hanging Plant 2" },
      { "custompiece_vines8", "Vines 8" },
      { "custompiece_vines9", "Vines 9" },
      { "custompiece_barrelcactus", "Barrel Cactus" },
      { "custompiece_cactus1", "Cactus 1" },
      { "custompiece_cactus1.2", "Cactus 1.2" },
      { "custompiece_cactus2", "Cactus 2" },
      { "custompiece_desertlily", "Desert Lily" },
      { "custompiece_desertmarigold", "Desert Marigold" },
      { "custompiece_evergladespalm", "Everglades Palm" },
      { "custompiece_hibiscusflower", "Hibiscus Flower" },
      { "custompiece_ivorycanepalm", "Ivory Cane Palm" },
      { "custompiece_ladypalm", "Lady Palm" },
      { "custompiece_pricklypear", "Prickly Pear" },
      { "custompiece_venusflytrap", "Venus FLy Trap" },
      { "custompiece_aeonium", "Aeonium" },
      { "custompiece_aloe", "Aloe" },
      { "custompiece_bromeliad", "Bromeliad" },
      { "custompiece_ivy1", "Ivy 1" },
      { "custompiece_ivy1.2", "Ivy 2" },
      { "custompiece_cattail", "Cattail" },
      { "custompiece_kelp", "Kelp" },
      { "custompiece_kelpbig", "Kelp (L)" },
      { "custompiece_rosevine", "Rosevine" },
      { "custompiece_tallflowerbush", "Tall Flower Bush" },
      { "custompiece_vines2", "Vines 2" },
      { "$custompiece_blackpine", "Blackpine" },
      { "custompiece_birdofparadise", "Bird of Paradise" },
      { "custompiece_bonsai", "Bonsai" },
      { "custompiece_coffeeplant", "Coffee Plant" },
      { "custompiece_fiddleleaf", "Fiddleleaf" },
      { "custompiece_littlehouseplant", "Little House Plant" },
      { "custompiece_orchid", "Orchid" },
      { "custompiece_spikyplant", "Spiky Plant" },
      { "custompiece_umbrellapalm", "Umbrellapalm" },
      { "custompiece_rubberfig", "Rubberfig" },
      { "custompiece_tallhouseplant", "Tall House Plant" },
      { "custompiece_aeoniums", "Aeoniums" },
      { "custompiece_bamboo", "Bamboo" },
      { "custompiece_coolpot", "Cool Pot" },
      { "custompiece_miscplant1", "Misc Plant 1" },
      { "custompiece_miscplant2", "Misc Plant 2" },
      { "custompiece_orchid2", "Orchid 2" },
      { "custompiece_pottedcactus1", "Potted Cactus 1" },
      { "custompiece_pottedcactus2", "Potted Cactus 2" },
      { "custompiece_smallpottedplant", "Small Potted Plant" },
      { "custompiece_weirdflowers", "Weird Flowers" },
      { "$custompiece_s1_roundcactuspinkflowers", "Round Cactus Pink Flowers" },
      { "$custompiece_s2_tallcactusredflower", "Tall Cactus Red Flower" },
      { "$custompiece_s3_pottedpricklypear", "Potted Prickly Pear" },
      { "$custompiece_s4_snakeplant", "Snake Plant" },
      { "$custompiece_s5_aloe", "Aloe" },
      { "$custompiece_s6_pachy", "Pachy" },
      { "$custompiece_s7_calisunset", "Calisunset" },
      { "$custompiece_s8_towercactus", "Towercactus" },
      { "$custompiece_s9_whiteflowers", "White Flowers" },
      { "$custompiece_s10_fatboi", "Fat boi" },
      { "$custompiece_s11_clehmannii", "Clehmannii" },
      { "$custompiece_s11_cLehmannii", "Clehmannii" },
      { "$custompiece_s12_splitrocks", "Split Rocks" },
      { "$custompiece_s13_roundcactusyellowflowers", "Round Cactus Yellow Flowers" },
      { "$custompiece_s14_roseaeonium", "Rose Aeonium" },
      { "$custompiece_s15_euphorbia", "Euphorbia" }
    };

    public static string GetName(string assetName) {
      if (_displayNames.ContainsKey(assetName)) {
        return _displayNames[assetName];
      }

      return assetName;
    }
  }
}
